# Generated by Django 3.1.2 on 2021-04-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barril',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True)),
                ('capacidad', models.IntegerField(blank=True, default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Fermentado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha fin')),
                ('litros_entrada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros de entrada')),
                ('litros_salida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros de salida')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_produccion', models.DateTimeField(verbose_name='Fecha')),
                ('cantidad_agua', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Litros de agua usados')),
                ('temperatura_maceracion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura de macerado')),
                ('temperatura_coccion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura cocción')),
                ('tiempo_coccion', models.TimeField(verbose_name='Tiempo de cocción')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llenado', models.DateTimeField()),
                ('fecha_carbonatado', models.DateTimeField()),
                ('barriles', models.ManyToManyField(to='produccion.Barril')),
                ('id_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.produccion')),
            ],
        ),
    ]
