# Generated by Django 3.1.7 on 2021-05-01 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_auto_20210430_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barril',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('capacidad', models.IntegerField(blank=True, default='0')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='sin descripcion')),
                ('fecha_produccion', models.DateTimeField(verbose_name='Fecha')),
                ('cantidad_agua', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Litros de agua usados')),
                ('temperatura_maceracion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura de macerado')),
                ('tiempo_maceracion', models.DurationField(verbose_name='Tiempo maceracion')),
                ('temperatura_coccion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura cocción')),
                ('tiempo_coccion', models.DurationField(verbose_name='Tiempo de cocción')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llenado', models.DateField(verbose_name='Fecha llenado')),
                ('hora_llenado', models.TimeField(blank=True, verbose_name='Hora lleando')),
                ('fecha_carbonatado', models.DateField(verbose_name='Fecha carbonatado')),
                ('hora_carbonatado', models.TimeField(blank=True, verbose_name='Hora carbonatado')),
                ('activo', models.BooleanField(default=True)),
                ('barriles', models.ManyToManyField(to='produccion.Barril')),
                ('id_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.produccion', verbose_name='Produccion')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente_Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Cantidad de ingredientes usados')),
                ('ingrediente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='compras.ingrediente')),
                ('produccion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='produccion.produccion')),
            ],
        ),
        migrations.CreateModel(
            name='Fermentado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('litros_entrada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros de entrada')),
                ('litros_salida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros de salida')),
                ('activo', models.BooleanField(default=True)),
                ('produccion', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='produccion.produccion')),
            ],
        ),
    ]
