# Generated by Django 3.1.7 on 2021-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_auto_20210501_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='hora_carbonatado',
            field=models.TimeField(blank=True, default=0, verbose_name='Hora carbonatado'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='hora_llenado',
            field=models.TimeField(blank=True, default=0, verbose_name='Hora lleando'),
        ),
    ]
