# Generated by Django 3.1.7 on 2021-04-10 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20210402_1439'),
        ('produccion', '0004_auto_20210408_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente_produccion',
            name='ingrediente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='compras.ingrediente'),
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='produccion',
            name='ingrediente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='produccion.ingrediente_produccion'),
        ),
    ]
