# Generated by Django 3.1.7 on 2021-04-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20210402_1439'),
        ('produccion', '0005_auto_20210409_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente_produccion',
            name='produccion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='produccion.produccion'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='tiempo_maceracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tiempo de macerado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produccion',
            name='ingrediente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='compras.ingrediente'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='tiempo_coccion',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tiempo de cocción'),
        ),
    ]
