# Generated by Django 3.1.2 on 2021-04-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_auto_20210402_1439'),
        ('produccion', '0007_produccion_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='produccion',
            name='ingredientes',
            field=models.ManyToManyField(through='produccion.Ingrediente_Produccion', to='compras.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='descripcion',
            field=models.TextField(blank=True, default='sin descripcion'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='tiempo_coccion',
            field=models.DurationField(verbose_name='Tiempo de cocción'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='tiempo_maceracion',
            field=models.DurationField(verbose_name='Tiempo maceracion'),
        ),
    ]
