# Generated by Django 3.1.2 on 2021-04-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_auto_20210410_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='ingredientes',
        ),
    ]
