# Generated by Django 3.1.7 on 2021-04-02 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Stock en kg')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='Sin descripcion')),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateField(verbose_name='Fecha de compra')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comentario', models.TextField(blank=True)),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.ingrediente', verbose_name='Ingrediente')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.proveedor', verbose_name='Proveedor')),
            ],
        ),
    ]
