# Generated by Django 3.1.7 on 2021-05-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='comentario',
            field=models.TextField(blank=True, default='Sin comentarios'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Stock en kg'),
        ),
    ]
