# Generated by Django 3.1.7 on 2021-04-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_vencimiento',
            field=models.DateField(null=True, verbose_name='Fecha de vencimiento'),
        ),
    ]
