# Generated by Django 3.1.7 on 2021-05-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20210430_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
