# Generated by Django 3.1.7 on 2021-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
