# Generated by Django 3.1.7 on 2021-04-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20210411_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='comentario',
            field=models.TextField(blank=True, default='Sin comentarios'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Stock en kg'),
        ),
    ]
