# Generated by Django 3.1.2 on 2021-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20210411_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Stock en kg'),
        ),
    ]
