# Generated by Django 3.1.7 on 2021-05-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forma_de_pago',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
