# Generated by Django 3.1.7 on 2021-04-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
