# Generated by Django 3.1.7 on 2021-04-30 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_clientes_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='mail',
            new_name='email',
        ),
    ]
