# Generated by Django 3.1.7 on 2021-04-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20210429_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situacion_frente_iva',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
